places = {
    'ГК "Гладенькая"': {
        'coordinates': (52.927255, 91.361045),
        'phone': '+79233933300',
        'url': 'http://ski-gladenkaya.ru',
        'webcam': 'http://ski-gladenkaya.ru/ski/webcam.html',
        'trail_map': 'gla.jpg',
        'info': {
            'trails': 3,
            'max_length': 4.2,
            'total_length': 8,
            'vertical_drop': 920,
            'max_elevation': 1747,
            'lifts': 3,
            'type_lift': 'кресельный, бугельный',
            },
    },
    'ГК "Черёмуховый лог"': {
        'coordinates': (52.853902, 91.408986),
        'phone': '+73904231216',
        'url': 'http://info-borus.ru/ski/',
        'webcam': None,
        'trail_map': None,
        'info': {
            'trails': 2,
            'max_length': 1,
            'total_length': 1.6,
            'vertical_drop': 160,
            'max_elevation': 555,
            'lifts': 1,
            'type_lift': 'кресельный',
            },
    },
    'База "Ергаки"': {
        'coordinates': (52.837717, 93.255870),
        'phone': '88007076270',
        'url': 'http://ergaki.com/',
        'webcam': None,
        'trail_map': 'ergaki.jpg',
        'info': {
            'trails': 1,
            'max_length': 1.2,
            'total_length': 1.2,
            'vertical_drop': 250,
            'max_elevation': 1680,
            'lifts': 1,
            'type_lift': 'бугельный',
            },
    },
    'База "Снежная" (Ергаки)': {
        'coordinates': (52.799549, 93.268188),
        'phone': '+79083272930\n+79029968773',
        'url': 'https://snow611.ru/',
        'webcam': None,
        'trail_map': None,
        'info': {
            'trails': 1,
            'max_length': 1.6,
            'total_length': 1.6,
            'vertical_drop': 330,
            'max_elevation': 1750,
            'lifts': 1,
            'type_lift': 'бугельный',
            },
    },
    'Пик Звёздный (Ергаки)': {
        'coordinates': (52.829201, 93.300938),
        'phone': '+79503040055',
        'url': 'http://ergaki-sayan.ru/zvezdnyi/',
        'webcam': None,
        'trail_map': None,
        'info': {
            'trails': 'нет данных',
            'max_length': 'нет данных',
            'total_length': 'нет данных',
            'vertical_drop': 'нет данных',
            'max_elevation': 'нет данных',
            'lifts': 'нет данных',
            'type_lift': 'нет данных',
            },
    },
    'Тушканчик кэмп (Ергаки)': {
        'coordinates': (52.803941, 93.247428),
        'phone': '88005003448',
        'url': 'https://tushkanchik.camp/',
        'webcam': None,
        'trail_map': None,
        'info': {
            'trails': 1,
            'max_length': 1.8,
            'total_length': 1.8,
            'vertical_drop': 400,
            'max_elevation': 1797,
            'lifts': 1,
            'type_lift': 'бугельный',
            },
    },
    'ГК "Бобровый лог"': {
        'coordinates': (55.962128, 92.794737),
        'phone': '+73912568686',
        'url': 'https://bobrovylog.ru/',
        'webcam': 'https://bobrovylog.ru/about/webcam/',
        'trail_map': 'bobr_log.jpg',
        'info': {
            'trails': 15,
            'max_length': 1.6,
            'total_length': 11,
            'vertical_drop': 350,
            'max_elevation': 517,
            'lifts': 4,
            'type_lift': 'кресельный, бугельный',
            },
    },
    'Приисковый': {
        'coordinates': (54.652993, 88.703671),
        'phone': '88005003449',
        'url': 'https://priiskovy.ru/',
        'webcam': None,
        'trail_map': None,
        'info': {
            'trails': 7,
            'max_length': 1.7,
            'total_length': 9.8,
            'vertical_drop': 400,
            'max_elevation': 1657,
            'lifts': 0,
            'type_lift': 'сноукэты, снегоходы',
            },
    },
    'Шерегеш': {
        'coordinates': (52.947942, 87.932612),
        'phone': '',
        'url': 'https://gesh.ru/',
        'webcam': 'https://gesh.ru/webcamera/',
        'trail_map': 'gesh.jpg',
        'info': {
            'trails': 15,
            'max_length': 4.2,
            'total_length': 36.9,
            'vertical_drop': 680,
            'max_elevation': 1270,
            'lifts': 19,
            'type_lift': 'гондольный, кресельный, бугельный',
            },
    },
    'ГК "Оленья подкова"': {
        'coordinates': (54.345838, 93.250253),
        'phone': '+79024688352',
        'url': 'https://vk.com/gora_korona/',
        'webcam': None,
        'trail_map': None,
        'info': {
            'trails': 1,
            'max_length': 1,
            'total_length': 1,
            'vertical_drop': 160,
            'max_elevation': 650,
            'lifts': 1,
            'type_lift': 'бугельный',
            },
    },
    'ГК "Сюгеш"': {
        'coordinates': (52.717182, 89.918972),
        'phone': '+79833779577',
        'url': 'https://sugesh.ru/',
        'webcam': None,
        'trail_map': None,
        'info': {
            'trails': 0.75,
            'max_length': 0.75,
            'total_length': 0.75,
            'vertical_drop': 120,
            'max_elevation': 670,
            'lifts': 1,
            'type_lift': 'бугельный',
            },
    },
}
