version: '3.3'

services:
  bot:
    image: hlystovea/sayanbot:latest
    container_name: sayanbot_bot
    restart: always
    command: python3 main.py
    env_file:
      - ./.env

  mongodb:
    image: mongo # 4.4.10
    container_name: sayanbot_mongodb
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - mongodb-data:/data/db
    depends_on:
      - bot

networks:
  default:
    name: sayanbot_network
    driver: bridge

volumes:
  mongodb-data:
