version: '3.3'

services:
  bot:
    image: "${DOCKER_HUB}/sayanbot:latest"
    container_name: sayanbot_bot
    restart: unless-stopped
    command: python3 bot.py
    env_file:
      - ./.env

  mongodb:
    image: mongo
    container_name: sayanbot_mongodb
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - mongodb-data:/data/db
    depends_on:
      - bot

networks:
  default:
    name: sayanbot_network
    driver: bridge

volumes:
  mongodb-data:
