version: '3.3'

services:
  bot:
    image: hlystovea/sayanbot:latest
    container_name: sayanbot
    restart: always
    command: python3 main.py
    env_file:
      - ./.env

  mongodb:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
    - mongodb-data:/data/db
    networks:
    - mongodb_network
    ports:
    - 27017:27017

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
    - mongodb-data
    depends_on:
    - mongodb
    networks:
    - mongodb_network
    ports:
    - 8081:8081

volumes:
  mongodb-data:

networks:
  mongodb_network:
